name: main
on:
  push:
    branches: [main]

  # To run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://alibaghdadi1368:$HF_TOKEN@huggingface.co/spaces/AliBaghdadi1368/Absenteeism main
